-- H2 2.3.232; 
;              
CREATE USER IF NOT EXISTS "SA" SALT '56be8b15f2cdc6cb' HASH '8407a61c40c11c7adf5b1ccd7678ab73607ac8a6c861582c53c1d0be4cdae01f' ADMIN;          
CREATE MEMORY TABLE "PUBLIC"."SECTOR"(
    "HIERARCHY_LEVEL" INTEGER,
    "PARENT_ID" BIGINT,
    "SECTOR_ID" BIGINT NOT NULL,
    "SECTOR_NAME" CHARACTER VARYING(255) NOT NULL
);            
ALTER TABLE "PUBLIC"."SECTOR" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("SECTOR_ID"); 
-- 79 +/- SELECT COUNT(*) FROM PUBLIC.SECTOR;  
INSERT INTO "PUBLIC"."SECTOR" VALUES
(NULL, NULL, 1, 'Manufacturing'),
(NULL, NULL, 2, 'Service'),
(NULL, NULL, 3, 'Other'),
(NULL, 1, 5, 'Printing'),
(NULL, 1, 6, 'Food and Beverage'),
(NULL, 1, 7, 'Textile and Clothing'),
(NULL, 1, 8, 'Wood'),
(NULL, 1, 9, 'Plastic and Rubber'),
(NULL, 1, 11, 'Metalworking'),
(NULL, 1, 12, 'Machinery'),
(NULL, 1, 13, 'Furniture'),
(NULL, 1, 18, 'Electronics and Optics'),
(NULL, 1, 19, 'Construction materials'),
(NULL, 2, 21, 'Transport and Logistics'),
(NULL, 2, 22, 'Tourism'),
(NULL, 2, 25, 'Business services'),
(NULL, 2, 28, 'Information Technology and Telecommunications'),
(NULL, 3, 29, 'Energy technology'),
(NULL, 3, 33, 'Environment'),
(NULL, 2, 35, 'Engineering'),
(NULL, 3, 37, 'Creative industries'),
(NULL, 6, 39, 'Milk & dairy products'),
(NULL, 6, 40, 'Meat & meat products'),
(NULL, 6, 42, 'Fish & fish products'),
(NULL, 6, 43, 'Beverages'),
(NULL, 7, 44, 'Clothing'),
(NULL, 7, 45, 'Textile'),
(NULL, 8, 47, 'Wooden houses'),
(NULL, 8, 51, 'Wooden building materials'),
(NULL, 559, 53, 'Plastics welding and processing'),
(NULL, 9, 54, 'Packaging'),
(NULL, 559, 55, 'Blowing'),
(NULL, 559, 57, 'Moulding'),
(NULL, 542, 62, 'Forgings, Fasteners'),
(NULL, 542, 66, 'MIG, TIG, Aluminum welding'),
(NULL, 11, 67, 'Construction of metal structures'),
(NULL, 542, 69, 'Gas, Plasma, Laser cutting'),
(NULL, 542, 75, 'CNC-machining'),
(NULL, 12, 91, 'Machinery equipment/tools'),
(NULL, 12, 93, 'Metal structures'),
(NULL, 12, 94, 'Machinery components'),
(NULL, 12, 97, 'Maritime'),
(NULL, 13, 98, 'Kitchen'),
(NULL, 13, 99, 'Project furniture'),
(NULL, 13, 101, 'Living room'),
(NULL, 21, 111, 'Air'),
(NULL, 21, 112, 'Road'),
(NULL, 21, 113, 'Water'),
(NULL, 21, 114, 'Rail'),
(NULL, 28, 121, 'Software, Hardware'),
(NULL, 28, 122, 'Telecommunications'),
(NULL, 2, 141, 'Translation services'),
(NULL, 5, 145, 'Labelling and packaging printing'),
(NULL, 5, 148, 'Advertising'),
(NULL, 5, 150, 'Book/Periodicals printing'),
(NULL, 12, 224, 'Manufacture of machinery'),
(NULL, 12, 227, 'Repair and maintenance service'),
(NULL, 97, 230, 'Ship repair and conversion'),
(NULL, 11, 263, 'Houses and buildings'),
(NULL, 11, 267, 'Metal products'),
(NULL, 97, 269, 'Boat/Yacht building'),
(NULL, 97, 271, 'Aluminium and steel workboats'),
(NULL, 8, 337, 'Other (Wood)'),
(NULL, 13, 341, 'Outdoor'),
(NULL, 6, 342, 'Bakery & confectionery products'),
(NULL, 6, 378, 'Sweets & snack food'),
(NULL, 13, 385, 'Bedroom'),
(NULL, 13, 389, 'Bathroom/sauna'),
(NULL, 13, 390, U&'Children\2019s room'),
(NULL, 13, 392, 'Office'),
(NULL, 13, 394, 'Other (Furniture)'),
(NULL, 6, 437, 'Other'),
(NULL, 12, 508, 'Other'),
(NULL, 11, 542, 'Metal works'),
(NULL, 9, 556, 'Plastic goods'),
(NULL, 9, 559, 'Plastic processing technology'),
(NULL, 9, 560, 'Plastic profiles'),
(NULL, 28, 576, 'Programming, Consultancy'),
(NULL, 28, 581, 'Data processing, Web portals, E-marketing');               
CREATE MEMORY TABLE "PUBLIC"."USER_SELECTION_SECTOR"(
    "SECTOR_ID" BIGINT NOT NULL,
    "USER_SELECTION_ID" BIGINT NOT NULL
);              
ALTER TABLE "PUBLIC"."USER_SELECTION_SECTOR" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("SECTOR_ID", "USER_SELECTION_ID");             
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.USER_SELECTION_SECTOR;    
INSERT INTO "PUBLIC"."USER_SELECTION_SECTOR" VALUES
(111, 1),
(114, 1),
(112, 1),
(113, 1);    
CREATE MEMORY TABLE "PUBLIC"."USER_SELECTION"(
    "AGREE_TO_TERMS" BOOLEAN NOT NULL,
    "USER_SELECTION_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 2) NOT NULL,
    "USER_NAME" CHARACTER VARYING(255) NOT NULL
);
ALTER TABLE "PUBLIC"."USER_SELECTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("USER_SELECTION_ID"); 
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.USER_SELECTION;           
INSERT INTO "PUBLIC"."USER_SELECTION" VALUES
(TRUE, 1, 'testUser01');          
ALTER TABLE "PUBLIC"."SECTOR" ADD CONSTRAINT "PUBLIC"."FKN6JFOE213MLNAFOAIAOLVH5C8" FOREIGN KEY("PARENT_ID") REFERENCES "PUBLIC"."SECTOR"("SECTOR_ID") NOCHECK;
ALTER TABLE "PUBLIC"."USER_SELECTION_SECTOR" ADD CONSTRAINT "PUBLIC"."FKFBBPC9NKQ5T1KGTGUA57L0P85" FOREIGN KEY("SECTOR_ID") REFERENCES "PUBLIC"."SECTOR"("SECTOR_ID") NOCHECK; 
ALTER TABLE "PUBLIC"."USER_SELECTION_SECTOR" ADD CONSTRAINT "PUBLIC"."FKMR1K2Q29F7KBC2XHATA13IWS9" FOREIGN KEY("USER_SELECTION_ID") REFERENCES "PUBLIC"."USER_SELECTION"("USER_SELECTION_ID") NOCHECK;         
